// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc2619.Resistance2019.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.PIDCommand;
import edu.wpi.first.wpilibj.smartdashboard.SmartDashboard;

import org.usfirst.frc2619.Resistance2019.Robot;
import org.usfirst.frc2619.Resistance2019.VisionData;
import org.usfirst.frc2619.Resistance2019.VisionUtil;

/**
 *
 */
public class TurnToVisionTarget extends PIDCommand {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
 
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    VisionData camInfo;

    Timer timeWithoutTarget;
    private static final double TIMEOUT = 0.5;
    private boolean timerIsRunning;

    private boolean targetFound;

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public TurnToVisionTarget() {

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        super("TurnToVisionTarget",  0.035, 0.0, 0.0002, 0.2);
        getPIDController().setAbsoluteTolerance(0.2);
        getPIDController().setContinuous(false);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING

        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        requires(Robot.driveTrain);

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    @Override
    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        SmartDashboard.putNumber("Angle to closest target", camInfo.findYawOfClosestTarget());
        SmartDashboard.putNumber("Distance to closest target", camInfo.findClosestTargetDistance().getDistance());
        SmartDashboard.putBoolean("Vision PIDfunction hasTargets", camInfo.hasTargets());

        if (camInfo.hasTargets()) {
            double targetYaw = camInfo.findYawOfClosestTarget();
            return targetYaw;
        } else {
            return 0.0;
        }
        
    }

    @Override
    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT

        SmartDashboard.putBoolean("Vision PIDout hasTargets", camInfo.hasTargets());    

        try {
            if (camInfo.hasTargets()) {
                if (!targetFound)
                    targetFound = true;

                Robot.driveTrain.run(output, -output);
                SmartDashboard.putNumber("Vision Output", output);

                timerIsRunning = false;
                timeWithoutTarget.reset();
                timeWithoutTarget.stop();
            } else {
                if (!timerIsRunning) {
                    timeWithoutTarget.start();
                    timerIsRunning = true;
                }
                if (timeWithoutTarget.get() > TIMEOUT)
                    Robot.driveTrain.run(0.0, 0.0);
            }
        } catch(Exception e) {
            Robot.driveTrain.run(0.0, 0.0);
        }
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        timerIsRunning = false;
        targetFound = false;

        Robot.driveTrain.setPercentVBus();
        getPIDController().setSetpoint(0.0);
        timeWithoutTarget = new Timer();
        timeWithoutTarget.stop();
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute() {
        camInfo = VisionUtil.getSerialInfo(Robot.visionPort);
        SmartDashboard.putNumber("Vision Timer", timeWithoutTarget.get());
        SmartDashboard.putBoolean("Vision On Target", getPIDController().onTarget());
        SmartDashboard.putNumber("Vision Error", getPIDController().getError());
        SmartDashboard.putNumber("Vision time passed", timeSinceInitialized());

    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished() {
        if (camInfo.hasTargets())
            return getPIDController().onTarget();
        else if (timeWithoutTarget.get() <= TIMEOUT || timeSinceInitialized() <= TIMEOUT)
            return false;
        else if (timeSinceInitialized() > TIMEOUT && !targetFound)
            return true;
        else
            return true;
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.driveTrain.stop();
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
        end();
    }
}
